services:
  auth-service:
    image: ghcr.io/prismedroiteext/bzhspauth
    restart: unless-stopped
    ports:
      - "8082:8082"
    environment:
      - AUTH_DB_HOST=${AUTH_DB_HOST}
      - AUTH_DB_USER=${AUTH_DB_USER}
      - AUTH_DB_PASSWORD=${AUTH_DB_PASSWORD}
      - AUTH_DB_NAME=${AUTH_DB_NAME}
      - DB_PORT=${DB_PORT}
      - DB_SSLMODE=${DB_SSLMODE}
      - DB_TIMEZONE=${TIMEZONE}
      - GIN_MODE=${GIN_MODE}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - db-auth


  db-auth:
    image: postgres:17
    environment:
      POSTGRES_USER: ${AUTH_DB_USER}
      POSTGRES_PASSWORD: ${AUTH_DB_PASSWORD}
      POSTGRES_DB: ${AUTH_DB_NAME}
    volumes:
      - ../volumes/auth-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
