apiVersion: v1
kind: Namespace
metadata:
  name: bzhspback
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-config
  namespace: bzhspback
data:
  DB_PORT: "5432"
  DB_SSLMODE: "disable"
  DB_TIMEZONE: "Europe/Paris"
  GIN_MODE: "release"
---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: bzhspback
type: Opaque
data:
  AUTH_DB_USER: YXV0aF91c2Vy
  AUTH_DB_PASSWORD: cG9zdGdyZXM=
  AUTH_DB_NAME: YXV0aF9kYg==
  JWT_SECRET: bXlzdXBlcnNlY3JldGtleQ==
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: bzhspback
spec:
  selector:
    app: auth-service
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: bzhspback
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: auth-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8082
        env:
        - name: AUTH_DB_HOST
          value: auth-db-service
        envFrom:
        - configMapRef:
            name: auth-config
        - secretRef:
            name: auth-secrets
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-db
  namespace: bzhspback
spec:
  serviceName: auth-db-service
  replicas: 1
  selector:
    matchLabels:
      app: auth-db
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: postgres
        image: postgres:17
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: AUTH_DB_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: AUTH_DB_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: AUTH_DB_NAME
        volumeMounts:
        - name: auth-db-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: auth-db-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  namespace: bzhspback
spec:
  selector:
    app: auth-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  clusterIP: None