# Automatically generate documentation using Swaggo's swag library
name: Generate Docs

on:
  pull_request:
    branches: ["main", "dev"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  docgen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Swag  
        working-directory: app
        run: |
          go mod tidy
          go get -u github.com/swaggo/swag/cmd/swag
          go get -u github.com/swaggo/gin-swagger
          go get -u github.com/swaggo/files
          
      - name: Generate Docs
        working-directory: app/cmd/web
        run: go run github.com/swaggo/swag/cmd/swag init --parseDependency --parseInternal

      - name: Create branch and commit changes
        run: |
          # Check if there are any changes
          if [[ -n "$(git status --porcelain)" ]]; then
            # Changes exist, create branch and commit
            branch_name="docs/api-update-$(date +%Y%m%d-%H%M%S)"
            echo "branch_name=$branch_name" >> $GITHUB_ENV
            
            # Configure git
            git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git config --local user.name "github-actions[bot]"
            
            # Commit and push changes
            git checkout -b $branch_name
            git add .
            git commit -m "docs: update API documentation"
            git push origin $branch_name
            echo "changes_exist=true" >> $GITHUB_ENV
          else
            echo "No changes detected in the documentation"
            echo "changes_exist=false" >> $GITHUB_ENV
          fi

      - name: Create Pull Request
        if: env.changes_exist == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: 'docs: Update API Documentation'
          body: |
            Automated PR to update API documentation
            
            Generated by GitHub Actions workflow
          branch: ${{ env.branch_name }}
          base: dev
          labels: documentation