# Automatically generate documentation using Swaggo's swag library
name: Generate Docs

on:
  pull_request:
    branches: ["main", "dev"]

jobs:
  docgen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.23

      - name: Install Swag  
        working-directory: app
        run: |
          go mod tidy
          go get -u github.com/swaggo/swag/cmd/swag
          go get -u github.com/swaggo/gin-swagger
          go get -u github.com/swaggo/files
          
      - name: Generate Docs
        working-directory: app/cmd/web
        run: go run github.com/swaggo/swag/cmd/swag init --parseDependency --parseInternal

      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
        
      - name: Commit and push changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git pull origin ${{ github.head_ref }}
          git add .
          git commit -m "docs: update API documentation" || echo "No changes to commit"
          git push origin HEAD:${{ github.head_ref }}
