name: Update SuperApp Submodule

on:
  pull_request:
    branches: [dev]

jobs:
  update-submodules:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Allows pushing changes back to the repository
    steps:
      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
          ssh-key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          submodules: recursive
          persist-credentials: false  # Prevents default token from overriding SSH

      - name: Configure Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          if [ -n "$(git status --porcelain)" ]; then
            git add .
            git commit -m "Update submodules to latest commits on dev branch"
            git push origin HEAD:${{ github.head_ref }}
          else
            echo "No changes to commit"
          fi